/**
 * Minify HTML content
 * 
 * @param {string} html - The HTML content to minify
 *  
 * @returns {string} - The minified HTML content
 */

import { minify } from 'html-minifier'

export function minifyHtml(html) {
  return minify(html, {
    includeAutoGeneratedTags: true,
    removeAttributeQuotes: true,
    removeComments: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    sortClassName: true,
    useShortDoctype: true,
    collapseWhitespace: true
  
  })
}